auto: true

markdown: rdiscount
pygments: true
paginate: 8
permalink: /:title

title: Sachin
url: http://sachincode.github.io
feed: /atom.xml
author_info: <a href="http://sachincode.github.io/">Sachin</a>
